### ISSUE TITLE
Throw useful exception when JSON serialization or deserialization fails

### ISSUE THREAD

**Issue by chrisguitarguy** [elasticsearch/elasticsearch-php#175]
I have an application right now where I'm seeing a lot of errors like this:

```
Elasticsearch\Common\Exceptions\BadRequest400Exception -- {"error":"RemoteTransportException[[ip-10-0-3-88][inet[/10.0.3.88:9300]][indices:data/write/index]]; nested: MapperParsingException[failed to parse, document is empty]; ","status":400}
```

It's happening because serialization of the request body is failing (I know this because I tried to log a that body with `json_encode` and showing nothing).

I think this library should check [`json_last_error`](http://php.net/manual/en/function.json-last-error.php) in its [serializers](https://github.com/elasticsearch/elasticsearch-php/tree/master/src/Elasticsearch/Serializers) and throw a meaningful exception about the serialization failure.

I'd be happy to submit a pull request for this if you'd like.

**Comment by polyfractal** [comment]
Ah, are you submitting raw JSON to the client rather than associative arrays?

:+1:  I agree, the client should throw a proper exception instead of waiting for the server to complain.  

Pull requests very welcome!  Perhaps we could take the logic from [SmartSerializer->decode()](https://github.com/elasticsearch/elasticsearch-php/blob/master/src/Elasticsearch/Serializers/SmartSerializer.php#L87-L98) and make it more general, since it already does a similar reporting process for decoding invalid JSON?  Would be nice if that logic could be used for both encode and decode.

**Comment by chrisguitarguy** [comment]
> are you submitting raw JSON to the client rather than associative arrays

Nope, trying to submit associative arrays. I'm guessing it's a UTF8 issue, but I haven't been able to nail that down yet. Just got to the point of realizing what was causing the error.

> Would be nice if that logic could be used for both encode and decode.

Agreed! I was thinking of just adding an abstract class for all json serializer to inherit from. encode/decode methods and a check method that runs after each to find the error (if any).

Would you want to maintain [this](https://github.com/elasticsearch/elasticsearch-php/blob/master/src/Elasticsearch/Serializers/SmartSerializer.php#L91)?

**Comment by polyfractal** [comment]
> Nope, trying to submit associative arrays. I'm guessing it's a UTF8 issue, but I haven't been able to nail that down yet. Just got to the point of realizing what was causing the error.

Oh, weird.  Let me know if you want some help debugging, in case it's the client mangling the JSON somehow.

> Agreed! I was thinking of just adding an abstract class for all json serializer to inherit from. encode/decode methods and a check method that runs after each to find the error (if any).

Yep, that seems like the best approach.  I'd either implement a concrete `checkJsonError()` in the abstract class, or just provide `json_encode()` and `json_decode` implementations that can be called by the subclasses, instead of the standard PHP one.  I'm favorable to the second option, since that is similar to how [Nette](https://github.com/nette/utils/blob/master/src/Utils/Json.php) implemented their handler and I'd like to pull that code for 2.0.

> Would you want to maintain this?

Hmm, I'm looking at this again and it's buggy:  it won't throw JSON-related exceptions if E_NOTICE is disabled.  This was done to prevent notices being [spammed from integer overflows](https://github.com/elasticsearch/elasticsearch-php/pull/146), but it has the side-effect of ignoring legit JSON errors.

I think we should remove the check for E_NOTICE and always throw exceptions, because that is the Right Thing To Do.  Its unclear to me if this is a breaking change (since you need to check for exceptions now) or simply an additional "feature" (since you now know when JSON fails).  

I'm inclined to tag it as a new minor version, since pushing a major for a single exception seems a bit overkill :)

**Comment by chrisguitarguy** [comment]
> Oh, weird. Let me know if you want some help debugging, in case it's the client mangling the JSON somehow.

I suspect its invalid UTF-8 characters that I'm trying to insert. I'm stuck on silex (#167) and v1.1 of Elasticsearch PHP so I'm rolling my own serializer class to throw some exceptions and get a better picture of what's going on.

**Comment by polyfractal** [comment]
Gotcha.

FWIW, I've been working on ES-PHP 2.0 for the last week or two and have removed Pimple as a dependency, so it should become friendly to any version of Silex again.  Not ETA on the release yet, but hopefully sooner than later :)
