### ISSUE TITLE
Get all documents in percolator

### ISSUE THREAD

**Issue by maxttor** [elasticsearch/elasticsearch-php#178]
How i can get all documents in percolator?
Or how i can get document in percolator by id ?
Or how i can check on existing document ?

**Comment by polyfractal** [comment]
Do you mean, how to get all registered percolator queries?  The percolator stores registered queries, not documents.

**Comment by maxttor** [comment]
yes, correct

**Comment by polyfractal** [comment]
>How i can get all documents in percolator?

Registered queries are stored in a special `.percolator` type in the index, so you can execute a search to get them:

```php
$response = $client->search([
    'index' => 'myindex',
    'type' => '.percolator',
    'size' => 100
]);
```

If you have more than a few hundred, you might want to use scan/scroll instead of a regular search for performance reasons

> Or how i can get document in percolator by id ?

Similarly, since these are documents in the `.percolator` type, you can do a normal GET by ID:

```php
$response = $client->get([
    'index' => 'myindex',
    'type' => '.percolator',
    'id' => 'percolator_abc'
]);
```

> Or how i can check on existing document ?

You can percolate existing docs using the [parameters listed here](http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/search-percolate.html#_percolating_an_existing_document).  For example:

```php

$response = $client->percolate([
    'index' => 'transactions',
    'type' => 'widgets',
    'id' => '12345',
    'percolate_index' => 'percolate_index'
]);
```
