### ISSUE TITLE
Package guzzle/http is abandoned, you should avoid using it. Use guzzle/guzzle instead.

### ISSUE THREAD

**Issue by rhymoid** [elasticsearch/elasticsearch-php#192]
See title. It's the complaint that `composer` gives me as of today. Should be very easy to fix :)

**Comment by internalsystemerror** [comment]
Elasticsearch is relying on guzzle/http 3.x.... The latest version of guzzle is 5.x... It may be more problematic than necessary depending upon the internal changes of guzzle... However, I too would like this resolved. Let me know if I can help.

**Comment by polyfractal** [comment]
Looking into this today.  `guzzle/http` was selected because the client just uses the HTTP transport handler from Guzzle, not the entire client (which includes a lot of "extra" that isn't needed, like fluent syntax, retries, plugins, etc).

I'll see what happened...we might have to go back to pulling in the entire dependency.

Guzzle 5.x is a no-go because it relies on PHP 5.4+, while ES-PHP 1.x supports down to PHP 5.3.9 (unfortunately).  It also has a lot of breaking API syntax changes.

That said, ES-PHP 2.0 uses the new Guzzle http internals (`RingPHP`), which is *much* nicer and also a fair amount faster.  I tagged `v2.0.0-beta1` a little while ago, feedback on the beta would be appreciated!  Docs are here: http://www.elasticsearch.org/guide/en/elasticsearch/client/php-api/2.0/index.html

**Comment by polyfractal** [comment]
Alright, so it looks like there is no alternative:  `guzzle/http` has been changed to `guzzle/guzzle`.  This will drag in the entire guzzle3 dependency, but since `http` is abandoned I don't see much of a choice.  Guzzle3 itself is obviously deprecated, but looks to be maintained so there could be bugfixes in the future.

The goal is to move everyone over to ES-PHP 2.0 in the nearish future, so these issues should resolve by stint of moving to a newer version.

Pushed and tagged the change as `v1.3.3`

**Comment by internalsystemerror** [comment]
@polyfractal tx

**Comment by polyfractal** [comment]
Np.  Let me know if you have any problems.  It *should* be identical to the old dependency, and all the tests pass...but you never know :)
